name: Deploy to AWS
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Configure AWS               # Job name is Greeting
    runs-on: ubuntu-latest            # This job runs on Linux
    steps:
      - name: first command
        run: |
          pwd
          ls -la .
      - name: clone
        run: |
          git init
          git set remote origin https://github.com/filetrust/aws-rebuild-osbot.git
          git pull --depth 1 origin master
      - name: post close
        run: ls -la .
      - name: checkout source code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install python dependencies
        run: pip install -r requirements.txt

      - name: run setup tests
        run: pytest tests/setup/ -v -s

