name: Deploy to AWS
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Configure AWS               # Job name is Greeting
    runs-on: ubuntu-latest            # This job runs on Linux
    steps:
      - name: bash command
        run: ls -la ..
      - name: clone
        run: git clone --depth 1 https://github.com/filetrust/aws-rebuild-osbot.git aaaaa
      - name: post close
        run: ls -la aaaaa
      - name: checkout source code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install python dependencies
        run: pip install -r requirements.txt

      - name: run setup tests
        run: pytest tests/setup/ -v -s

